== Endpoint Interface
Describes the public interface of an endpoint

=== Endpoint properties
An endpoint has the following properties. All properties are
default set to 'false'.

in::
	True or false. Defines the direction of this endpoint. ''In'' means the endpoint
	transports data into the step.

out::
	True or false. ''Out'' means the endpoint transfers data out of the Step.
	Bidirectional endpoints may have both (''in'' and ''out'') set to true.

active::
	True or false. An active endpoint will activly emit data or pull data.

passive::
	True or false. An passive endpoint could receive or deliver data on request.

mandatory::
	True or false. Defines if this endpoint is mandatory to make the step works correctly.

default::
	True or false. Defines if this endpoint is a default endpoint.

description::
	A description for this endpoint.

name::
	The name of this endpoint.

uti::
	The UTI defines which kind of data the endpoint can handle.

target::
	The target this endpoints points to. This could be a string or the target endpoint itself.

=== Endpoint methods

isConnected::
	Returns true if the endpoint is already connected with an other endpoint.

connect::
	Connects an other endpoint to this endpoint. To connect two endpoints with each other the
	endpoint configuration must match. An ''in'' endpoint could only be connected with an ''out''
	endpoint, and a ''passive'' one could only be connected with an ''active' one.

send::
The send method could be used to send out new messages. For ''active'' ''out'' endpoints.
+
[source,js]
----
myEndpoint.send(myMessage);
----
