== Step Interface
Describes the step interface. Each step need to implement the methods of this step interface.


=== Step properties

name::
Returns the name of the step. For the 'raw' step as it will be registered at the kronos-manager the name will
be the same as the type.

endpoints::
Returns an object with all the endpoints of this step.

[source,js]
----
{
	"name1" : endpoint1,
}
----

=== Step methods

start::
Starts the step. If a step is started it is able to retrieve requests over its endpoints.
The start method will return a Promise with the step itself after it is fullfiled.

stop::
Stops a step. When a step will be stopped it should disable the inbound endpoints first. So no new request
could come in.

isRunning::
Returns a true value if the step is running. This means it is not stopped.


getInstance::
This function creates a new instance of this step. This method is used if a flow needs step instances.

[source,js]
----
/**
 * Returns a new step instance with the given configuration
 * @param {Manager} manager
 * @param {Object} scopeReporter (optional) This reporter is used to report parsing errors.
 *                               If not given the scopereporter from the manager will be taken
 * @param {Object} stepConfiguration The default step configuration
 * @api protected
 */
getInstance(manager, scopeReporter, stepConfiguration)
----

toString::


toJSON::
